content:
  - name: posts
    label: Posts
    path: '_posts'
    type: collection
    fields: 
      - name: layout
        label: Layout
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: date 
        label: Date, 
        type: date
      - name: author
        label: author
        type: string
      - name: categories
        label: categories
        type: string  
      - name: short_description
        label: short_description
        type: string
      - name: external_url
        label: External Url
        type: link
      - name: body
        label: Body
        type: rich-text

media: images