# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tom Barbereau
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Dr. Tom Barbereau.
repository: https://github.com/wemake-services/jekyll-theme-hackcss
baseurl: /  # the subpath of your site, e.g. /blog
url: https://tom-barbereau.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: tom barbereau
email: tom.barbereau@tno.nl

navigation:
  - text: Home
    url: /
  - text: Blog
    url: /blog
  - text: Portfolio
    url: https://scholar.google.com/citations?user=qvsfsEMAAAAJ&hl=en
    target: "_blank"
  - text: Contact
    url: /contact

projects:
  - name: git-secret
    description: A bash-tool to store your private data inside a git repository.
    link: https://sobolevn.github.io/git-secret
    image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true
  - name: googlescholar
    description: 
    link: https://scholar.google.com/citations?user=qvsfsEMAAAAJ&hl=en
    image: 
  - name: ecto_autoslug_field
    description: Automatically creates slugs for your Ecto models.
    link: https://github.com/sobolevn/ecto_autoslug_field
  - name: django-split-settings
    description: Organize Django settings into multiple files and directories. Easily override and modify settings. Use wildcards and optional settings files.
    link: https://github.com/sobolevn/django-split-settings

social:
  - service: github
    username: github
    link: https://github.com/tom-barbereau
  - service: twitter
    username: twitter
    link: https://twitter.com/TomBarbereau
  - service: linkedin
    username: linkedin
    link: https://linkedin.com/tom-barbereau
  - service: googlescholar
    username: googlescholar
    link: https://scholar.google.com/citations?user=qvsfsEMAAAAJ&hl=en
  - service: telegram
    username: telegram
    link: https://t.me/tombarbereau

# Plugins
gems:
  - jekyll-seo-tag
